route_admin_subjects:
    path: /
    defaults: { _controller: RobiskApplicationBundle:Admin/SubjectAdmin:index }

route_admin_subject_add:
    path: /add
    defaults: { _controller: RobiskApplicationBundle:Admin/SubjectAdmin:add }

route_admin_subject_edit:
    path: /edit/{id}
    defaults: { _controller: RobiskApplicationBundle:Admin/SubjectAdmin:edit, id: 0 }

route_admin_subject_user_approve:
    path: /edit/{id}/approve/{userId}
    defaults: { _controller: RobiskApplicationBundle:Admin/SubjectAdmin:approveUser, id: 0, userId: 0 }

route_admin_subject_user_approve_all:
    path: /edit/{id}/approve-all
    defaults: { _controller: RobiskApplicationBundle:Admin/SubjectAdmin:approveAllUsers, id: 0 }

route_admin_subject_user_decline:
    path: /edit/{id}/decline/{userId}
    defaults: { _controller: RobiskApplicationBundle:Admin/SubjectAdmin:declineUser, id: 0, userId: 0 }

route_admin_subject_user_valuation:
    path: /user-valuation/{id}/{userId}
    defaults: { _controller: RobiskApplicationBundle:Admin/SubjectAdmin:userValuation, id: 0, userId: 0 }

route_admin_subject_user_presentation:
    path: /user-presentation/{id}/{userId}
    defaults: { _controller: RobiskApplicationBundle:Admin/SubjectAdmin:userPresentation, id: 0, userId: 0 }

route_admin_subject_user_presentation_download:
    path: /user-presentation-download/{id}/{userId}
    defaults: { _controller: RobiskApplicationBundle:Admin/SubjectAdmin:presentationDownload, id: 0, userId: 0 }

route_admin_subject_user_presentation_set_status:
    path: /user-presentation-set-status/{id}/{userId}/{status}
    defaults: { _controller: RobiskApplicationBundle:Admin/SubjectAdmin:setPresentationStatus, id: 0, userId: 0, status: 0 }

route_admin_subject_attendance_add:
    path: /attendance/add/{id}
    defaults: { _controller: RobiskApplicationBundle:Admin/SubjectAdmin:addAttendance, id: 0 }

route_admin_subject_attendance_lock:
    path: /attendance/lock/{id}
    defaults: { _controller: RobiskApplicationBundle:Admin/SubjectAdmin:lockAttendance, id: 0 }

route_admin_subject_attendance_students:
    path: /attendance/students/{id}
    defaults: { _controller: RobiskApplicationBundle:Admin/SubjectAdmin:viewStudentsAttendance, id: 0 }

route_admin_subject_settings:
    path: /settings/{id}
    defaults: { _controller: RobiskApplicationBundle:Admin/SubjectAdmin:settings, id: 0 }

route_admin_subject_change_status:
    path: /change-status/{id}
    defaults: { _controller: RobiskApplicationBundle:Admin/SubjectAdmin:changeStatus, id: 0 }

route_admin_subject_presentation_valuation_point_add:
    path: /presentation-valuation-point/add/{id}
    defaults: { _controller: RobiskApplicationBundle:Admin/SubjectAdmin:addPresentationValuationPoint, id: 0 }

route_admin_subject_presentation_valuation_point_save:
    path: /presentation-valuation-point/save/{id}
    defaults: { _controller: RobiskApplicationBundle:Admin/SubjectAdmin:savePresentationValuationPoint, id: 0 }

route_admin_subject_presentation_valuation_point_delete:
    path: /presentation-valuation-point/delete/{id}/{pvpId}
    defaults: { _controller: RobiskApplicationBundle:Admin/SubjectAdmin:deletePresentationValuationPoint, id: 0, pvpId: 0 }

route_teacher_presentations:
    path: edit/{id}/teacher-presentations
    defaults: { _controller: RobiskApplicationBundle:Admin/SubjectAdmin:teacherPresentations, id: 0}

route_send_mail:
    path: edit/{id}/send-mail
    defaults: { _controller: RobiskApplicationBundle:Admin/SubjectAdmin:sendMail, id: 0}
