parameters:
#    robisk_application.example.class: Robisk\ApplicationBundle\Example

services:
#    robisk_application.example:
#        class: %robisk_application.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    manager_announcement:
        class: Robisk\ApplicationBundle\Doctrine\Manager\AnnouncementManager
        arguments: [@doctrine.orm.entity_manager, Robisk\ApplicationBundle\Entity\Announcement, @service_container]

    manager_announcement_frontend:
        class: Robisk\ApplicationBundle\Doctrine\Manager\AnnouncementFrontendManager
        arguments: [@doctrine.orm.entity_manager, Robisk\ApplicationBundle\Entity\AnnouncementFrontend, @service_container]

    manager_user:
        class: Robisk\ApplicationBundle\Doctrine\Manager\UserManager
        arguments: [@doctrine.orm.entity_manager, Robisk\ApplicationBundle\Entity\User, @service_container]

    manager_user_subject_lookup:
        class: Robisk\ApplicationBundle\Doctrine\Manager\UserSubjectLookupManager
        arguments: [@doctrine.orm.entity_manager, Robisk\ApplicationBundle\Entity\UserSubjectLookup, @service_container]

    manager_user_attendance_lookup:
        class: Robisk\ApplicationBundle\Doctrine\Manager\UserAttendanceLookupManager
        arguments: [@doctrine.orm.entity_manager, Robisk\ApplicationBundle\Entity\UserAttendanceLookup, @service_container]

    manager_subject:
        class: Robisk\ApplicationBundle\Doctrine\Manager\SubjectManager
        arguments: [@doctrine.orm.entity_manager, Robisk\ApplicationBundle\Entity\Subject, @service_container]

    manager_subject_valuation:
        class: Robisk\ApplicationBundle\Doctrine\Manager\SubjectValuationManager
        arguments: [@doctrine.orm.entity_manager, Robisk\ApplicationBundle\Entity\SubjectValuation, @service_container]

    manager_teacher_presentation:
        class: Robisk\ApplicationBundle\Doctrine\Manager\TeacherPresentationManager
        arguments: [@doctrine.orm.entity_manager, Robisk\ApplicationBundle\Entity\TeacherPresentation, @service_container]

    manager_attendance:
        class: Robisk\ApplicationBundle\Doctrine\Manager\AttendanceManager
        arguments: [@doctrine.orm.entity_manager, Robisk\ApplicationBundle\Entity\Attendance, @service_container]

    manager_presentation:
        class: Robisk\ApplicationBundle\Doctrine\Manager\PresentationManager
        arguments: [@doctrine.orm.entity_manager, Robisk\ApplicationBundle\Entity\Presentation, @service_container]

    manager_presentation_valuation_point:
        class: Robisk\ApplicationBundle\Doctrine\Manager\PresentationValuationPointManager
        arguments: [@doctrine.orm.entity_manager, Robisk\ApplicationBundle\Entity\PresentationValuationPoint, @service_container]

    manager_user_presentation_valuation:
        class: Robisk\ApplicationBundle\Doctrine\Manager\UserPresentationValuationManager
        arguments: [@doctrine.orm.entity_manager, Robisk\ApplicationBundle\Entity\UserPresentationValuation, @service_container]

    manager_user_subject_presentation_lookup:
        class: Robisk\ApplicationBundle\Doctrine\Manager\UserSubjectPresentationLookupManager
        arguments: [@doctrine.orm.entity_manager, Robisk\ApplicationBundle\Entity\UserSubjectPresentationLookup, @service_container]

    manager_user_presentation_comments:
        class: Robisk\ApplicationBundle\Doctrine\Manager\UserPresentationCommentsManager
        arguments: [@doctrine.orm.entity_manager, Robisk\ApplicationBundle\Entity\UserPresentationCommentsManager, @service_container]

    manager_announcement_comments:
        class: Robisk\ApplicationBundle\Doctrine\Manager\AnnouncementCommentsManager
        arguments: [@doctrine.orm.entity_manager, Robisk\ApplicationBundle\Entity\AnnouncementComments, @service_container]

    manager_teacher_presentation_comments:
        class: Robisk\ApplicationBundle\Doctrine\Manager\TeacherPresentationCommentsManager
        arguments: [@doctrine.orm.entity_manager, Robisk\ApplicationBundle\Entity\TeacherPresentationComments, @service_container]   
