parameters:

services:
    service.twig.user:
        class: Robisk\ApplicationBundle\Twig\UserExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    service.twig.subject:
            class: Robisk\ApplicationBundle\Twig\SubjectExtension
            arguments: [@service_container]
            tags:
                - { name: twig.extension }