route_home:
    pattern: /{_locale}
    defaults: { _controller: RobiskApplicationBundle:Static:index, _locale: 'sk' }

route_subjects:
    pattern: /{_locale}/subjects
    defaults: { _controller: RobiskApplicationBundle:Subject:index, _locale: 'sk' }

route_subject_user_add:
    pattern: /{_locale}/subjects/add/{id}
    defaults: { _controller: RobiskApplicationBundle:User:addSubject, _locale: 'sk', id: 0 }

route_subject_view:
    pattern: /{_locale}/subject/{id}
    defaults: { _controller: RobiskApplicationBundle:Subject:view, _locale: 'sk', id: 0 }

route_subject_announcements:
    pattern: /{_locale}/subject/{id}/announcements
    defaults: { _controller: RobiskApplicationBundle:Subject:announcements, _locale: 'sk', id: 0 }

route_subject_presentation_upload:
    pattern: /{_locale}/subject/{id}/presentation-upload
    defaults: { _controller: RobiskApplicationBundle:Subject:presentationUpload, _locale: 'sk', id: 0 }

route_subject_presentation_download:
    pattern: /{_locale}/subject/{id}/presentation-download/{presentationId}
    defaults: { _controller: RobiskApplicationBundle:Subject:presentationDownload, _locale: 'sk', id: 0, presentationId: 0 }

route_subject_presentation_delete:
    pattern: /{_locale}/subject/{id}/presentation-delete/{presentationId}
    defaults: { _controller: RobiskApplicationBundle:Subject:presentationDelete, _locale: 'sk', id: 0, presentationId: 0 }

route_subject_presentation_add_user:
    pattern: /{_locale}/subject/{id}/presentation/{presentationId}/add-user
    defaults: { _controller: RobiskApplicationBundle:Subject:presentationAddUser, _locale: 'sk', id: 0, presentationId: 0 }

route_subject_presentation_delete_user:
    pattern: /{_locale}/subject/{id}/presentation/{presentationId}/delete-user/{userId}
    defaults: { _controller: RobiskApplicationBundle:Subject:presentationDeleteUser, _locale: 'sk', id: 0, presentationId: 0, userId: 0 }

route_subject_presentation_valuating:
    pattern: /{_locale}/subject/{id}/presentation-valuating/{userId}
    defaults: { _controller: RobiskApplicationBundle:Subject:presentationValuating, _locale: 'sk', id: 0, userId: 0 }

route_subject_user_attendance_add:
    pattern: /{_locale}/attendance-add/{id}
    defaults: { _controller: RobiskApplicationBundle:User:addAttendance, _locale: 'sk', id: 0 }

route_subject_teacher_presentation:
    pattern: /{_locale}/teacher-presentation/{id}
    defaults: { _controller: RobiskApplicationBundle:Subject:teacherPresentationView, _locale: 'sk', id: 0 }

route_subject_announcements_forum:
    pattern: /{_locale}/subject/diskusia/announcements/{id}/{announcementId}
    defaults: { _controller: RobiskApplicationBundle:Comment:announcementUserForum, _locale: 'sk', id: 0 , announcementId: 0}

route_subject_announcements_forum_delete:
    pattern: /{_locale}/subject/announcements/diskusia/delete/{id}/{announcementId}/{commentId}
    defaults: { _controller: RobiskApplicationBundle:Comment:announcementUserForumDelete, _locale: 'sk', id: 0 , announcementId: 0, commentId: 0}

route_subject_teacher_presentations_forum:
    pattern: /{_locale}/subject/teacher-presentation/diskusia/{id}/{presentationId}
    defaults: { _controller: RobiskApplicationBundle:Comment:teacherPresentationUserForum, _locale: 'sk', id: 0 , presentationId: 0}

route_subject_teacher_presentations_forum_delete:
    pattern: /{_locale}/subject/teacher-presentation/diskusia//delete/{id}/{presentationId}/{commentId}
    defaults: { _controller: RobiskApplicationBundle:Comment:teacherPresentationUserForumDelete, _locale: 'sk', id: 0 , presentationId: 0, commentId: 0}