application:
    resource: "@RobiskApplicationBundle/Resources/config/routing/frontend.yml"
    prefix:   /

application_admin:
    resource: "@RobiskApplicationBundle/Resources/config/routing/admin.yml"
    prefix:   /{_locale}/admin

application_registration:
    resource: "@RobiskApplicationBundle/Resources/config/routing/user.yml"
    prefix:   /{_locale}/
    defaults: { _locale: 'sk' }

login:
    path:     /{_locale}/login
    defaults: { _controller: RobiskApplicationBundle:Security:login, _locale: 'sk' }

login_check:
    path: /{_locale}/login_check
    defaults: { _locale: 'sk' }

logout:
    path: /{_locale}/logout
    defaults: { _locale: 'sk' }