security:
#    providers:
#        in_memory:
#            memory: ~
#
#    firewalls:
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        default:
#            anonymous: ~
    providers:
        main:
            entity:
                class: Robisk\ApplicationBundle\Entity\User
                property: username
        in_memory:
            memory: ~

    firewalls:
        login_firewall:
            pattern:   ^/login$
            anonymous: ~
        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   logout

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: ROLE_ADMIN }

    encoders:
        Robisk\ApplicationBundle\Entity\User: 
            algorithm: sha512
            iterations: 1
